# Generated by Django 2.0.13 on 2019-03-18 08:18

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(default='', max_length=255, unique=True)),
                ('author', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=112), blank=True, default=list, size=None)),
                ('country', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(default='', max_length=1024, verbose_name='Description')),
                ('chapters', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Chapters')),
                ('poster_url', models.URLField(blank=True, default='https://media.istockphoto.com/vectors/blank-book-cover-vector-id466036957?k=6&m=466036957&s=612x612&w=0&h=SHDzHMVV6CHMNk6P-7igrYcZTfGryYdk_J7jzf7MwyY=', max_length=255, verbose_name='Poster URL')),
                ('volumes', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(default=0), size=2), blank=True, default=list, size=None)),
                ('votes', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Votes')),
                ('votes_external', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Votes External')),
                ('rating', models.FloatField(blank=True, default=0.0, verbose_name='Rating')),
                ('ranking', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Ranking')),
                ('status', models.IntegerField(choices=[(0, 'published'), (1, 'draft')], default=0)),
                ('published_at', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', when={'published'})),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='BookChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(default='', max_length=255, unique=True)),
                ('text', models.TextField(default='')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookchapters', related_query_name='bookchapter', to='books.Book')),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(default='', max_length=112, verbose_name='Genre')),
                ('slug', models.SlugField(max_length=112, unique=True)),
            ],
            options={
                'verbose_name': 'Book Genre',
                'verbose_name_plural': 'Book Genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(default='', max_length=112, verbose_name='Tag')),
                ('slug', models.SlugField(max_length=112, unique=True)),
            ],
            options={
                'verbose_name': 'Book Tag',
                'verbose_name_plural': 'Book Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='bookgenre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', related_query_name='book', to='books.BookGenre'),
        ),
        migrations.AddField(
            model_name='book',
            name='booktag',
            field=models.ManyToManyField(related_name='books', to='books.BookTag'),
        ),
    ]
