# Generated by Django 2.0.13 on 2019-03-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1024, verbose_name='Description'),
        ),
    ]
