# Generated by Django 2.0.13 on 2019-03-14 08:58

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190313_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='poster_url',
            field=models.URLField(blank=True, default='https://media.istockphoto.com/vectors/blank-book-cover-vector-id466036957?k=6&m=466036957&s=612x612&w=0&h=SHDzHMVV6CHMNk6P-7igrYcZTfGryYdk_J7jzf7MwyY=', max_length=255, verbose_name='Poster URL'),
        ),
        migrations.AddField(
            model_name='book',
            name='published_at',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', when={'published'}),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Rating'),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='unpublished', max_length=100, no_check_for_status=True),
        ),
        migrations.AddField(
            model_name='book',
            name='votes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Votes'),
        ),
        migrations.AddField(
            model_name='book',
            name='votes_external',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Votes External'),
        ),
    ]
