# Generated by Django 2.0.13 on 2019-03-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190318_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status_release',
            field=models.IntegerField(choices=[(0, 'ongoing'), (1, 'completed')], default=0),
        ),
    ]
