# Generated by Django 2.1.7 on 2019-05-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookchapter_allow_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='country',
            field=models.CharField(blank=True, choices=[('china', 'China'), ('korea', 'Korea'), ('japan', 'Japan')], default='china', max_length=55),
        ),
    ]
