# Generated by Django 2.0.13 on 2019-03-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20190314_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='poster_url',
            field=models.URLField(blank=True, default='https://image.freepik.com/free-vector/blank-book-cover-template-with-pages-front-side-standing_47649-397.jpg', max_length=255, verbose_name='Poster URL'),
        ),
    ]
