# Generated by Django 2.1.7 on 2019-05-11 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_bookchapterreplace'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookchapterreplace',
            options={'verbose_name': 'Book Chapter Replace', 'verbose_name_plural': 'Book Chapter Replaces'},
        ),
    ]
