# Generated by Django 2.0.13 on 2019-03-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20190314_1200'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookVolume',
        ),
        migrations.AlterModelOptions(
            name='bookchapter',
            options={'ordering': ['pk'], 'verbose_name': 'Chapter', 'verbose_name_plural': 'Chapters'},
        ),
        migrations.AlterModelOptions(
            name='bookgenre',
            options={'ordering': ['name'], 'verbose_name': 'Book Genre', 'verbose_name_plural': 'Book Genres'},
        ),
        migrations.AlterModelOptions(
            name='booktag',
            options={'ordering': ['name'], 'verbose_name': 'Book Tag', 'verbose_name_plural': 'Book Tags'},
        ),
        migrations.AddField(
            model_name='bookchapter',
            name='chapter_count_id',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='poster_url',
            field=models.URLField(blank=True, default='https://media.istockphoto.com/vectors/blank-book-cover-vector-id466036957?k=6&m=466036957&s=612x612&w=0&h=SHDzHMVV6CHMNk6P-7igrYcZTfGryYdk_J7jzf7MwyY=', max_length=255, verbose_name='Poster URL'),
        ),
    ]
