# Generated by Django 2.1.7 on 2019-05-28 09:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20190511_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='similar',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(verbose_name='Similar books'), blank=True, default=list, size=None),
        ),
    ]
