# Generated by Django 2.0.13 on 2019-03-16 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20190316_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookchapter',
            old_name='chapter_count_id',
            new_name='_id',
        ),
    ]
