# Generated by Django 2.0.13 on 2019-03-16 15:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20190316_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookchapter',
            name='_id',
        ),
        migrations.AddField(
            model_name='bookchapter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
