# Generated by Django 2.0.13 on 2019-03-16 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20190316_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookchapter',
            name='created_at',
        ),
    ]
