# Generated by Django 2.0.13 on 2019-03-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_remove_bookchapter_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookchapter',
            name='count_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=1, null=True),
        ),
    ]
