# Generated by Django 2.0.13 on 2019-03-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20190318_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='visited_wn',
            field=models.BooleanField(default=False, verbose_name='WN scraped'),
        ),
        migrations.AddField(
            model_name='book',
            name='visitet_bn',
            field=models.BooleanField(default=False, verbose_name='BN scraped'),
        ),
    ]
