# Generated by Django 2.0.13 on 2019-03-17 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_bookchapter_count_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookchapter',
            name='count_id',
        ),
    ]
