# Generated by Django 2.0.13 on 2019-03-18 07:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_remove_bookchapter_count_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='volumes',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(default=0), size=2), blank=True, default=list, size=None),
        ),
    ]
