# Generated by Django 2.0.13 on 2019-03-19 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20190319_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='visitet_bn',
            new_name='visited_bn',
        ),
    ]
