# Generated by Django 2.0.13 on 2019-03-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20190319_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='chapters_release',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Chapters update'),
        ),
    ]
