# Generated by Django 2.0.13 on 2019-03-18 07:53

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_book_status_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status_release',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='unpublished', max_length=100, no_check_for_status=True, verbose_name=(('ongoing', 'ongoing'), ('completed', 'completed'))),
        ),
    ]
