# Generated by Django 2.0.13 on 2019-03-18 08:00

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20190318_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='status_release',
        ),
        migrations.AddField(
            model_name='book',
            name='ranking',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Ranking'),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='published', max_length=100, no_check_for_status=True),
        ),
    ]
