# Generated by Django 2.0.13 on 2019-03-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_book_title_sm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='booktag',
            field=models.ManyToManyField(blank=True, related_name='books', to='books.BookTag'),
        ),
    ]
