# Generated by Django 2.0.13 on 2019-03-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_auto_20190319_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='chapters_max',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Chapters Full'),
        ),
    ]
