# Generated by Django 2.0.13 on 2019-03-18 08:03

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_auto_20190318_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default=0, max_length=100, no_check_for_status=True),
        ),
    ]
