# Generated by Django 2.0.13 on 2019-03-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_book_chapters_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_id_bn',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='BN book id'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_id_wn',
            field=models.IntegerField(blank=True, default=0, max_length=255, verbose_name='WN book id'),
        ),
    ]
