# Generated by Django 2.0.13 on 2019-03-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_auto_20190319_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id_wn',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='WN book id'),
        ),
    ]
