# Generated by Django 2.0.13 on 2019-03-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_auto_20190319_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='locked_wn',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='WN locked from'),
        ),
    ]
