# Generated by Django 2.0.13 on 2019-03-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_book_locked_wn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.IntegerField(choices=[(0, 'draft'), (1, 'published')], default=1),
        ),
    ]
