# Generated by Django 2.0.13 on 2019-03-20 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0023_remove_book_locked_wn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='chapters_release',
        ),
    ]
