# Generated by Django 2.0.13 on 2019-03-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0024_remove_book_chapters_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='chapters_release',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Chapters update'),
        ),
    ]
