# Generated by Django 2.0.13 on 2019-03-22 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0025_book_chapters_release'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='chapters_max',
        ),
    ]
