# Generated by Django 2.0.13 on 2019-03-23 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0026_remove_book_chapters_max'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookchapter',
            options={'ordering': ['pk'], 'verbose_name': 'Book Chapter', 'verbose_name_plural': 'Book Chapters'},
        ),
    ]
