# Generated by Django 2.1.7 on 2019-03-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0027_auto_20190323_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.IntegerField(choices=[(0, 'draft'), (1, 'published')], db_index=True, default=1),
        ),
    ]
