# Generated by Django 2.1.7 on 2019-03-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0028_auto_20190325_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='ranking',
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.IntegerField(choices=[(0, 'draft'), (1, 'published')], db_index=True, default=0),
        ),
    ]
