# Generated by Django 2.1.7 on 2019-03-25 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0029_auto_20190325_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='votes_external',
        ),
    ]
