# Generated by Django 2.1.7 on 2019-03-26 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0030_remove_book_votes_external'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookchapter',
            options={'ordering': ['c_id'], 'verbose_name': 'Book Chapter', 'verbose_name_plural': 'Book Chapters'},
        ),
    ]
