# Generated by Django 2.1.7 on 2019-04-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0031_auto_20190326_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ranking',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Ranking'),
        ),
    ]
