# Generated by Django 2.1.7 on 2019-04-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0033_auto_20190415_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='revisit',
            field=models.CharField(choices=[('default', 'default'), ('webnovel', 'WebNovel'), ('boxnovel', 'BoxNovel'), ('wuxiaworld', 'WuxiaWorld')], default='default', max_length=55),
        ),
    ]
