# Generated by Django 2.1.7 on 2019-04-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0034_book_revisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='revisit',
            field=models.CharField(blank=True, choices=[('default', 'default'), ('webnovel', 'WebNovel'), ('boxnovel', 'BoxNovel'), ('wuxiaworld', 'WuxiaWorld')], default='default', max_length=55),
        ),
    ]
