# Generated by Django 2.1.7 on 2019-04-15 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0035_auto_20190415_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_id_bn',
            new_name='id_bn',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_id_wn',
            new_name='id_wn',
        ),
    ]
