# Generated by Django 2.1.7 on 2019-04-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0036_auto_20190415_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id_bn',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='BoxNovel id'),
        ),
        migrations.AlterField(
            model_name='book',
            name='id_wn',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='WebNovel id'),
        ),
        migrations.AlterField(
            model_name='book',
            name='visited_bn',
            field=models.BooleanField(default=False, verbose_name='BoxNovel visited'),
        ),
        migrations.AlterField(
            model_name='book',
            name='visited_wn',
            field=models.BooleanField(default=False, verbose_name='WebNovel visited'),
        ),
    ]
