# Generated by Django 2.1.7 on 2019-04-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0038_book_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='poster',
            field=models.ImageField(blank=True, default='posters/default.jpg', null=True, upload_to='posters/', verbose_name='Poster'),
        ),
    ]
