# Generated by Django 2.1.7 on 2019-04-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0040_remove_book_poster_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='revisit_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Revisit id'),
        ),
        migrations.AddField(
            model_name='book',
            name='visited',
            field=models.CharField(blank=True, choices=[('default', 'default (webnovel)'), ('boxnovel', 'BoxNovel'), ('wuxiaworld', 'WuxiaWorld')], default='default', max_length=55),
        ),
        migrations.AddField(
            model_name='book',
            name='visited_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Revisit id'),
        ),
        migrations.AlterField(
            model_name='book',
            name='revisit',
            field=models.CharField(blank=True, choices=[('default', 'default (webnovel)'), ('boxnovel', 'BoxNovel'), ('wuxiaworld', 'WuxiaWorld')], default='default', max_length=55),
        ),
    ]
