# Generated by Django 2.1.7 on 2019-04-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0041_auto_20190416_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id_bn',
        ),
        migrations.RemoveField(
            model_name='book',
            name='id_wn',
        ),
        migrations.RemoveField(
            model_name='book',
            name='visited_bn',
        ),
        migrations.RemoveField(
            model_name='book',
            name='visited_wn',
        ),
        migrations.AlterField(
            model_name='book',
            name='visited_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Visited id'),
        ),
    ]
