# Generated by Django 2.1.7 on 2019-04-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0042_auto_20190416_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='revisit',
            field=models.CharField(blank=True, choices=[('webnovel', 'Webnovel'), ('boxnovel', 'Boxnovel'), ('wuxiaworld', 'WuxiaWorld')], default='webnovel', max_length=55),
        ),
        migrations.AlterField(
            model_name='book',
            name='visited',
            field=models.CharField(blank=True, choices=[('webnovel', 'Webnovel'), ('boxnovel', 'Boxnovel'), ('wuxiaworld', 'WuxiaWorld')], default='webnovel', max_length=55),
        ),
    ]
