# Generated by Django 2.1.7 on 2019-04-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0044_auto_20190416_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='visited',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
