# Generated by Django 2.1.7 on 2019-04-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0045_book_visited'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='revisited',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
