# Generated by Django 2.1.7 on 2019-04-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0048_book_recommended'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='chapters',
            new_name='chapters_count',
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
    ]
