# Generated by Django 2.1.7 on 2019-04-22 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0050_auto_20190420_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='bookchapter',
            options={'verbose_name': 'Book Chapter', 'verbose_name_plural': 'Book Chapters'},
        ),
    ]
