# Generated by Django 2.1.7 on 2019-04-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0051_auto_20190422_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='allow_comments',
            field=models.BooleanField(default=True, verbose_name='allow comments'),
        ),
    ]
