# Generated by Django 2.1.7 on 2019-05-02 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments', '0003_add_submit_date_index'),
        ('books', '0053_bookcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcomment',
            name='xtdcomment_ptr',
        ),
        migrations.DeleteModel(
            name='BookComment',
        ),
    ]
