# Generated by Django 2.0.13 on 2019-03-23 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_bookprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookprogress',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookprogress',
            name='library',
        ),
        migrations.DeleteModel(
            name='BookProgress',
        ),
    ]
