# Generated by Django 2.0.13 on 2019-03-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_bookprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookprogress',
            name='c_id',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='Chapter ID'),
        ),
    ]
