# Generated by Django 2.0.13 on 2019-03-23 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190323_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookprogress',
            name='id',
        ),
        migrations.AlterField(
            model_name='bookprogress',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='books.Book'),
        ),
    ]
