# Generated by Django 2.1.7 on 2019-03-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20190326_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='votes',
            field=models.IntegerField(blank=True, default=3, null=True, verbose_name='Votes'),
        ),
    ]
