# Generated by Django 2.1.7 on 2019-04-11 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import novel2read.apps.users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profile_votes'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', novel2read.apps.users.managers.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='bookprogress',
            name='c_id',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='Progress ID'),
        ),
        migrations.AlterField(
            model_name='bookprogress',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookprogresses', to=settings.AUTH_USER_MODEL),
        ),
    ]
