# Generated by Django 2.1.7 on 2019-04-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20190414_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='premium_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
