# Generated by Django 2.1.7 on 2019-04-15 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20190414_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='premium_expire',
        ),
    ]
