# Generated by Django 2.1.7 on 2019-04-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_profile_premium_expire'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='premium_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
