# Generated by Django 2.1.7 on 2019-04-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_profile_premium_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='users/default.png', null=True, upload_to='users/', verbose_name='Avatar'),
        ),
    ]
