# Generated by Django 2.1.7 on 2019-04-20 17:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20190416_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookprogress',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
