# Generated by Django 2.1.7 on 2019-04-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_bookprogress_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookprogress',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
