# Generated by Django 2.1.7 on 2019-05-02 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basiccomment',
            old_name='avatar',
            new_name='user_avatar',
        ),
    ]
