# Generated by Django 2.1.7 on 2019-05-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20190502_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basiccomment',
            name='user_avatar',
            field=models.CharField(blank=True, default='users/default.png', max_length=255),
        ),
    ]
